name: drone_bridge_topics
from_domain: 11
to_domain: 0

topics:
  /drones/edu11/state:
    type: mavros_msgs/msg/State
    remap: /drone11/state
  /drones/edu11/mavros_node/pose:
    type: geometry_msgs/msg/PoseStamped
    remap: /drone11/odom
  /drones/edu11/battery:
    type: sensor_msgs/msg/BatteryState
    remap: /drone11/battery
  /drones/edu11/global_position/global:
    type: sensor_msgs/msg/NavSatFix
    remap: /drone11/gps
